site_name: OpenUSD Studierstube
site_description: "Documentation site following the NVIDIA OpenUSD Learning Path"

repo_url: https://github.com/perfectproducts/openusd_studierstube
repo_name: perfectproducts/openusd_studierstube

theme:
  name: material
  features:
    - navigation.instant
    - content.code.copy

nav:
  - Willkommen: index.md
  - Aufzeichnungen:
    - 2025-11-07 Composition Übungen: aufzeichnungen/2025-11-07/notes.md
    - 2025-10-31 Composition Basics: aufzeichnungen/2025-10-31/notes.md
    - 2025-10-24 Scene Blueprints B: aufzeichnungen/2025-10-24/notes.md
    - 2025-10-17 Scene Blueprints A: aufzeichnungen/2025-10-17/notes.md
    - 2025-10-10 Animations: aufzeichnungen/2025-10-10/notes.md
    - 2025-10-03 (Feiertag): https://www.tag-der-deutschen-einheit.de/startseite
    - 2025-09-26 Attributes: aufzeichnungen/2025-09-26/notes.md
    - 2025-09-19 Stages: aufzeichnungen/2025-09-19/notes.md
    - 2025-09-12 Einrichtung: aufzeichnungen/2025-09-12/notes.md

    
  - Material: material.md
  - Werkzeuge: tools.md
  - Über uns: about.md

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences